name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  provider: ^6.0.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  sqflite: ^2.4.1
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: ^0.5.0
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
